# Generated by Django 2.0.1 on 2018-02-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soapbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soapbox',
            options={'ordering': ['points']},
        ),
    ]
