# Generated by Django 2.0.1 on 2018-02-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soapbox', '0002_auto_20180208_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soapbox',
            options={'ordering': ['-points']},
        ),
    ]
