# Generated by Django 2.0.1 on 2018-02-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soapbox', '0003_auto_20180208_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='soapbox',
            name='team',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
