# Generated by Django 2.0.1 on 2018-02-22 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Soapbox', '0005_auto_20180222_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapbox',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
