# Generated by Django 2.0.1 on 2018-02-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soapbox', '0009_auto_20180223_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebuttal',
            name='parent_rebuttal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Soapbox.Rebuttal'),
        ),
        migrations.AlterField(
            model_name='rebuttal',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_soapbox', to='Soapbox.Soapbox'),
        ),
        migrations.AlterField(
            model_name='rebuttal',
            name='soapbox_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Soapbox.Soapbox'),
        ),
        migrations.AlterField(
            model_name='soapbox',
            name='created_at',
            field=models.DateTimeField(default='2018-02-23 08:35'),
        ),
    ]
