# Generated by Django 2.0.1 on 2018-02-23 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Soapbox', '0010_auto_20180223_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebuttalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=0)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoapboxVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=0)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rebuttal',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_soapbox', to='Soapbox.Soapbox'),
        ),
        migrations.AlterField(
            model_name='rebuttal',
            name='soapbox_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Soapbox.Soapbox'),
        ),
        migrations.AlterField(
            model_name='soapbox',
            name='created_at',
            field=models.DateTimeField(default='2018-02-23 13:10'),
        ),
        migrations.AddField(
            model_name='soapboxvote',
            name='soapbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soapbox.Soapbox'),
        ),
        migrations.AddField(
            model_name='rebuttalvote',
            name='rebuttal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soapbox.Rebuttal'),
        ),
        migrations.AlterUniqueTogether(
            name='soapboxvote',
            unique_together={('soapbox', 'customuser')},
        ),
        migrations.AlterUniqueTogether(
            name='rebuttalvote',
            unique_together={('rebuttal', 'customuser')},
        ),
    ]
