# Generated by Django 2.0.1 on 2018-01-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='No department specified', max_length=100),
        ),
    ]
