# Generated by Django 2.0.1 on 2018-01-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
