# Generated by Django 2.0.1 on 2018-03-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='somename',
        ),
    ]
