# Generated by Django 2.0.1 on 2018-01-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_auto_20180125_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Articles.Article'),
        ),
    ]
