# Generated by Django 2.0.1 on 2018-02-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_auto_20180126_1305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
    ]
